[build]
  functions = "netlify/functions"
  publish = "./netlify/functions/public"
  command = "npm install && npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200